### ISSUE TITLE
Error in docker-compose Splunk deployment when using kafka-sdm_1138.tgz

### ISSUE THREAD

**Issue by Alexbeav** [guilhemmarchand/kafka-docker-splunk#5]
Hello! First of all I would like to thank you on this magnificent lab, it is very helpful and impressive!

I believe there is a typo in your docker-compose.yml file under the Splunk section - when using the default cloned values, Splunk throws an error for kafka-sdm_1138.tgz (which is a directory), but you also include the file kafka-sdm_1141.tgz

Changing line 20 in the compose file from: 

      - ../kafka-smart-monitoring/telegraf-kafka_1138.tgz:/tmp/kafka-sdm.tgz

To

      - ../kafka-smart-monitoring/telegraf-kafka_1141.tgz:/tmp/kafka-sdm.tgz

Allows the installation to proceed properly, otherwise the Splunk container goes down after a few seconds.

Hope it helps!

**Comment by guilhemmarchand** [comment]
Hey @Alexbeav !

Thank you very much ;-) And many thanks for taking the time to share the issue, fixed now ;-)

Much appreciated!

Guilhem
